name: Build STARpp - Windows
on:
  workflow_call:
    secrets:
      qt_ffynnon_cred:
        description: 'Credentials for getting Qt from Ffynnon'
        required: true
    outputs:
      doc_artifact_name:
        description: "Name of artifact used to update docs"
        value: ${{ jobs.build-starpp.outputs.doc_artifact_name }}
env:
  qt_install_dir: ${{ github.workspace }}/Qt/Install
  starpp_src_suffix: STARpp/Source
  starpp_src_dir: ${{ github.workspace }}/STARpp/Source
  starpp_build_dir: ${{ github.workspace }}/STARpp/Build

jobs:
  build-starpp:
    name: Build STARpp - Windows (Release)
    strategy:
      fail-fast: false
      matrix:
        lib_linkage: [shared, static]
        include:
          - lib_linkage: shared
            cmake_bsl: ON
          - lib_linkage: static
            cmake_bsl: OFF
    runs-on: windows-latest
    env:
      vs_dir: C:/Program Files/Microsoft Visual Studio/2022/Enterprise
      cmake_gen: Ninja Multi-Config
    outputs:
      doc_artifact_name: ${{ steps.set_doc_artifact_name.outputs.doc_artifact_name }}
    steps:
    - name: Set derived variables with shell because GitHub Actions env context sucks
      run: |
        echo "starpp_package_path=${{ env.starpp_build_dir }}/out/dist" >> $Env:GITHUB_ENV
        $starpp_install_path="${{ env.starpp_build_dir }}/out/install"
        echo "starpp_install_path=$starpp_install_path" >> $Env:GITHUB_ENV
        echo "qt_cmake=${Env:qt_install_dir}/bin/qt-cmake.bat" >> $Env:GITHUB_ENV
    - name: Install Qt (custom build)
      uses: oblivioncth/actions/general/install-and-cache-qt-from-ffynnon@dev
      with:
        version: 6.4.2
        os: windows
        compiler: msvc2022
        linkage: ${{ matrix.lib_linkage }}
        path: ${{ env.qt_install_dir }}
        credentials: ${{ secrets.qt_ffynnon_cred }}
    - name: Install Doxygen & Graphviz
      run: |
        choco install doxygen.install --version 1.9.4
        choco install graphviz  
    - name: Checkout STARpp
      uses: actions/checkout@v3
      with:
        path: ${{ env.starpp_src_suffix }}
        fetch-depth: 0 # Required for verbose versioning to work correctly  
    - name: Build/Install STARpp
      working-directory: ${{ env.starpp_src_dir }}
      shell: cmd
      run: |
        echo "Setup C++ Build Environment..."
        CALL "${{ env.vs_dir }}\Common7\Tools\VsDevCmd.bat" -arch=amd64
        echo "Configure CMake using Qt wrapper..."
        CALL "${{ env.qt_cmake }}" -G "${{ env.cmake_gen }}" -S "${{ env.starpp_src_dir}}" -B "${{ env.starpp_build_dir }}" -D BUILD_SHARED_LIBS=${{ matrix.cmake_bsl }} -D STARPP_TESTS=ON -D STARPP_DOCS=ON
        echo "Changing to build directory..."
        cd "%starpp_build_dir%"
        echo "Building STARpp Release/Docs..."
        cmake --build . --target all --config Release
        echo "Installing STARpp Release/Docs..."
        cmake --install . --config Release
        echo "Packaging STARpp..."
        cpack -C "Release"
        echo "Running tests..."
        cmake --build . --target test --config Release
        echo "Build complete."
    - name: Remove VC Runtime Redistributable Added by Qt # Required until an option to disable this is added to Qt
      run: |
        Remove-Item "${{ env.starpp_install_path }}/bin/vc_redist*"
    - name: Get STARpp artifact name
      run: |
        $artifact_name=$((Get-ChildItem -Path "${{ env.starpp_package_path }}" -Filter *.zip)[0].BaseName)
        echo "current_artifact_name=$artifact_name" >> $Env:GITHUB_ENV
    - name: Set doc artifact name
      id: set_doc_artifact_name
      if: matrix.qt_linkage == 'static'
      run: echo "doc_artifact_name=$current_artifact_name" >> $Env:GITHUB_OUTPUT
    - name: Upload STARpp build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.current_artifact_name }}
        path: ${{ env.starpp_install_path }}
        if-no-files-found: error
