name: Master pull-request merge reaction
on:
  pull_request:
    types: [closed]
    branches:
    - 'master'
env:
  ci_bot_username: ObyBotCI
  ci_bot_email: 104651589+ObyBotCI@users.noreply.github.com
  starcalc_qtd_win_artifact_path: ${{ github.workspace }}/StarCalcQtDWin
  starcalc_qts_win_artifact_path: ${{ github.workspace }}/StarCalcQtSWin
  starcalc_qtd_linux_artifact_path: ${{ github.workspace }}/StarCalcQtDLinux
  starcalc_qts_linux_artifact_path: ${{ github.workspace }}/StarCalcQtSLinux
  
jobs:
  tag_master_and_sync_dev:
    name: Tag master merge commit, FF back to dev
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    outputs:
      new_version: ${{ steps.get-proj-ver.outputs.version }}
    steps:
    - name: Get project version
      id: get-proj-ver
      uses: oblivioncth/actions/cmake/get-project-version@dev
    - name: Set Git user to ObyBotCI
      uses: oblivioncth/actions/git/set-git-user-to-oby-bot@dev
    - name: Tag master with new version tag
      uses: oblivioncth/actions/git/tag@dev
      with:
        tag: 'v${{ steps.get-proj-ver.outputs.version }}'
        message: 'Release v${{ steps.get-proj-ver.outputs.version }}'
    - name: Move 'latest' tag
      uses: oblivioncth/actions/git/move-latest-tag@dev
    - name: Fast-forward merge master into to dev
      if: always()
      uses: oblivioncth/actions/git/merge-branches@dev
      with:
        source_branch: master
        target_branch: dev
        ff: only
        
  build_starcalc_release_windows:
    name: Build StarCalc Release (Windows)
    needs: tag_master_and_sync_dev
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/build-starcalc-windows.yml
    secrets:
      qt_static_url: ${{ secrets.QT_WINDOWS_STATIC_URL }}
      
  build_starcalc_release_linux:
    name: Build StarCalc Release (Linux)
    needs: tag_master_and_sync_dev
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/build-starcalc-linux.yml
    secrets:
      qt_static_url: ${{ secrets.QT_LINUX_STATIC_URL }}

  update-docs:
    name: Update gh-pages
    needs: [build_starcalc_release_windows]
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
    - name: Download built static StarCalc artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ needs.build_starcalc_release_windows.outputs.qt_static_artifact_name }}
        path: ${{ env.starcalc_qts_win_artifact_path }}
    - name: Upload docs to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ${{ env.starcalc_qts_win_artifact_path }}/doc/html
        destination_dir: ./docs
        allow_empty_commit: true # So that doc build date is always roughly synced with latest build date
        enable_jekyll: false
        user_name: '${{ env.ci_bot_username}}'
        user_email: '${{ env.ci_bot_email }}'
  create-release:
    name: Create GitHub release
    needs: [update-docs, build_starcalc_release_windows, build_starcalc_release_linux, tag_master_and_sync_dev]
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
    - name: Set release artifact names
      run: |
        echo "release_qtd_win_package_name=${{ needs.build_starcalc_release_windows.outputs.qt_shared_artifact_name }}" >> $Env:GITHUB_ENV
        echo "release_qts_win_package_name=${{ needs.build_starcalc_release_windows.outputs.qt_static_artifact_name }}" >> $Env:GITHUB_ENV
        echo "release_qtd_linux_package_name=${{ needs.build_starcalc_release_linux.outputs.qt_shared_artifact_name }}" >> $Env:GITHUB_ENV
        echo "release_qts_linux_package_name=${{ needs.build_starcalc_release_linux.outputs.qt_static_artifact_name }}" >> $Env:GITHUB_ENV
    - name: Download built shared Qx artifact (Windows)
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.release_qtd_win_package_name }}
        path: ${{ env.starcalc_qtd_win_artifact_path }}  
    - name: Download built static StarCalc artifact (Windows)
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.release_qts_win_package_name }}
        path: ${{ env.starcalc_qts_win_artifact_path }}
    - name: Download built shared Qx artifact (Linux)
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.release_qtd_linux_package_name }}
        path: ${{ env.starcalc_qtd_linux_artifact_path }}
    - name: Download built static StarCalc artifact (Linux)
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.release_qts_linux_package_name }}
        path: ${{ env.starcalc_qts_linux_artifact_path }}
    - name: Zip up release artifacts
      run: |
        7z a "${{ env.release_qtd_win_package_name }}.zip" "${{ env.starcalc_qtd_win_artifact_path }}/*"
        7z a "${{ env.release_qts_win_package_name }}.zip" "${{ env.starcalc_qts_win_artifact_path }}/*"
        7z a "${{ env.release_qtd_linux_package_name }}.zip" "${{ env.starcalc_qtd_linux_artifact_path }}/*"
        7z a "${{ env.release_qts_linux_package_name }}.zip" "${{ env.starcalc_qts_linux_artifact_path }}/*"
    - name: Generate release
      uses: softprops/action-gh-release@v1
      with:
        name: "StarCalc Release v${{ needs.tag_master_and_sync_dev.outputs.new_version }}"
        tag_name: "v${{ needs.tag_master_and_sync_dev.outputs.new_version }}"
        fail_on_unmatched_files: true
        generate_release_notes: true
        files: |
          ${{ env.release_qtd_win_package_name }}.zip
          ${{ env.release_qts_win_package_name }}.zip
          ${{ env.release_qtd_linux_package_name }}.zip
          ${{ env.release_qts_linux_package_name }}.zip
    
        