name: STARpp Push Reaction
on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'master'

jobs:
  trigger-windows-build:
    name: Build STARpp (Windows)
    uses: ./.github/workflows/build-starpp-windows.yml
    secrets:
      qt_ffynnon_cred: ${{ secrets.OBYBOT_FFYNNON_CREDS }}
      
  trigger-linux-build:
    name: Build STARpp (Linux)
    uses: ./.github/workflows/build-starpp-linux.yml
    secrets:
      qt_ffynnon_cred: ${{ secrets.OBYBOT_FFYNNON_CREDS }}