name: STARpp Push Reaction
on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'master'

jobs:
  trigger-windows-build:
    name: Build STARpp (Windows)
    uses: ./.github/workflows/build-starpp-windows.yml
    secrets:
      qt_shared_url: ${{ secrets.QT_WINDOWS_SHARED_URL }}
      qt_static_url: ${{ secrets.QT_WINDOWS_STATIC_URL }}
      
  trigger-linux-build:
    name: Build STARpp (Linux)
    uses: ./.github/workflows/build-starpp-linux.yml
    secrets:
      qt_shared_url: ${{ secrets.QT_LINUX_SHARED_URL }}
      qt_static_url: ${{ secrets.QT_LINUX_STATIC_URL }}